version: '3'
services:
  web:
    build: .
    ports:
      - "4001:4001"
    depends_on: 
      - redis
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
volumes:  
  redis_data: